services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
    - ./frontend:/usr/src/app
    - /usr/src/app/node_modules      
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
    
    # Vulnerability #4 - Exposed Docker Socket
    - /var/run/docker.sock:/var/run/docker.sock

    - ./backend:/usr/src/app
    - /usr/src/app/node_modules
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17.5-bookworm
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
volumes:
  postgres-data: