services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app:ro
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      # Vulnerability #4 - Overexposed Container Networking and Service Ports
      # Part 1/5 - Frontend isolated from database network.
      - public-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Vulnerability #5 - Backend container mounts host Docker socket directly - Out of scope here, addressed in its own section
      - /var/run/docker.sock:/var/run/docker.sock

      - ./backend:/usr/src/app:ro
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      # Vulnerability #4 - Overexposed Container Networking and Service Ports
      # Part 2/5 - Backend bridges public and private traffic boundaries.
      - public-network
      - private-network

  db:
    image: postgres:17.5-bookworm
    environment:
      # Vulnerability #6 - Postgres credentials stored as plaintext in compose - Out of scope here, addressed in its own section
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    # Vulnerability #4 - Overexposed Container Networking and Service Ports
    # Part 3/5 - Database port is no longer published to host.
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      # Vulnerability #4 - Overexposed Container Networking and Service Ports
      # Part 4/5 - Database attached only to private network.
      - private-network

networks:
  public-network:
    driver: bridge
  private-network:
    driver: bridge
    # Vulnerability #4 - Overexposed Container Networking and Service Ports
    # Part 5/5 - Internal-only network blocks external routing.
    internal: true

volumes:
  postgres-data: